CRYPTO_TOKENS = {
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "USDT": "Tether",
    "USDC": "USD Coin",
    "BNB": "Binance Coin",
    "XRP": "XRP",
    "ADA": "Cardano",
    "DOGE": "Dogecoin",
    "SOL": "Solana",
    "DOT": "Polkadot",
    "TRX": "TRON",
    "MATIC": "Polygon",
    "LTC": "Litecoin",
    "BCH": "Bitcoin Cash",
    "SHIB": "Shiba Inu",
    "AVAX": "Avalanche",
    "UNI": "Uniswap",
    "ATOM": "Cosmos",
    "LINK": "Chainlink",
    "ETC": "Ethereum Classic",
    "XLM": "Stellar",
    "ALGO": "Algorand",
    "VET": "VeChain",
    "HBAR": "Hedera",
    "ICP": "Internet Computer",
    "FIL": "Filecoin",
    "EGLD": "MultiversX",
    "APE": "ApeCoin",
    "AAVE": "Aave",
    "QNT": "Quant",
    "FTM": "Fantom",
    "NEAR": "Near Protocol",
    "XTZ": "Tezos",
    "GRT": "The Graph",
    "RUNE": "THORChain",
    "MANA": "Decentraland",
    "SAND": "The Sandbox",
    "AXS": "Axie Infinity",
    "FLOW": "Flow",
    "KLAY": "Klaytn",
    "EVMOS": "Evmos",
    "ZEC": "Zcash",
    "DASH": "Dash",
    "MIOTA": "IOTA",
    "XMR": "Monero",
    "WAVES": "Waves",
    "CRV": "Curve DAO Token",
    "CAKE": "PancakeSwap",
    "KSM": "Kusama",
    "ENJ": "Enjin Coin",
    "CHZ": "Chiliz",
    "ZIL": "Zilliqa",
    "1INCH": "1inch",
    "BAT": "Basic Attention Token",
    "OMG": "OMG Network",
    "STX": "Stacks",
    "SRM": "Serum",
    "BNT": "Bancor",
    "REN": "Ren",
    "HOT": "Holo",
    "AR": "Arweave",
    "DCR": "Decred",
    "COMP": "Compound",
    "YFI": "yearn.finance",
    "SNX": "Synthetix",
    "FTT": "FTX Token",
    "GALA": "Gala Games",
    "LRC": "Loopring",
    "CEL": "Celsius",
    "KNC": "Kyber Network",
    "ANKR": "Ankr",
    "RVN": "Ravencoin",
    "BTG": "Bitcoin Gold",
    "SC": "Siacoin",
    "XEM": "NEM",
    "QTUM": "Qtum",
    "ZEN": "Horizen",
    "ICX": "ICON",
    "ONT": "Ontology",
    "NANO": "Nano",
    "SUSHI": "SushiSwap",
    "CELO": "Celo",
    "OMG": "OMG Network",
    "STORJ": "Storj",
    "KAVA": "Kava",
    "GLM": "Golem",
    "OCEAN": "Ocean Protocol",
    "MASK": "Mask Network",
    "BAL": "Balancer",
    "UMA": "UMA",
    "ZRX": "0x",
    "IMX": "Immutable X",
    "HNT": "Helium",
    "DYDX": "dYdX",
    "RNDR": "Render Token",
    "OP": "Optimism",
    "ARB": "Arbitrum"
}
CURRENCY_LIST = {
    "USD": "United States Dollar",
    "EUR": "Euro",
    "JPY": "Japanese Yen",
    "GBP": "British Pound",
    "AUD": "Australian Dollar",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNY": "Chinese Yuan",
    "HKD": "Hong Kong Dollar",
    "NZD": "New Zealand Dollar",
    "SEK": "Swedish Krona",
    "KRW": "South Korean Won",
    "SGD": "Singapore Dollar",
    "NOK": "Norwegian Krone",
    "MXN": "Mexican Peso",
    "INR": "Indian Rupee",
    "RUB": "Russian Ruble",
    "ZAR": "South African Rand",
    "TRY": "Turkish Lira",
    "BRL": "Brazilian Real",
    "TWD": "New Taiwan Dollar",
    "DKK": "Danish Krone",
    "PLN": "Polish Zloty",
    "THB": "Thai Baht",
    "IDR": "Indonesian Rupiah",
    "HUF": "Hungarian Forint",
    "CZK": "Czech Koruna",
    "ILS": "Israeli Shekel",
    "CLP": "Chilean Peso",
    "PHP": "Philippine Peso",
    "AED": "UAE Dirham",
    "COP": "Colombian Peso",
    "SAR": "Saudi Riyal",
    "MYR": "Malaysian Ringgit",
    "RON": "Romanian Leu",
    "VND": "Vietnamese Dong",
    "PKR": "Pakistani Rupee",
    "BDT": "Bangladeshi Taka",
    "NGN": "Nigerian Naira",
    "QAR": "Qatari Riyal",
    "EGP": "Egyptian Pound",
    "KWD": "Kuwaiti Dinar",
    "BHD": "Bahraini Dinar",
    "OMR": "Omani Rial",
    "ARS": "Argentine Peso",
    "PEN": "Peruvian Sol",
    "KES": "Kenyan Shilling",
    "MAD": "Moroccan Dirham"
}


